name: jaguar_cache_redis
description: Cache implementation based on Redis
version: 2.1.1
homepage: https://github.com/Jaguar-dart/cache
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_cache: ^2.1.1
  resp_client: ^0.1.1
  jaguar_serializer: ^2.2.0

dev_dependencies:
  test: ^1.3.0
